name: deploy

on: 
    push:
        branches:
            - master

jobs:
    build-x1:
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
          - name: full checkout
            uses: actions/checkout@v3

          - name: Set up Python 3.8
            uses: actions/setup-python@v4            
            with:
              python-version: '3.10' 

          - name: Create a Release
            env:
              GITHUB_TOKEN: ${{ github.token }}
              # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              # GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}

              # Pass as an argument to an Action.
              # with:
              #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            run: |
              # pip install invoke pelican[markdown]
              pip install -r requirements.txt
              env > /tmp/x.env
              pelican content -s publishconf.py

              git branch -av

              ghp-import output -r . -p -m "abc roy"
              echo $GITHUB_TOKEN | sed -e 's/./& /g'

              git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
              git remote -v
              git push origin gh-pages
              # git push
              # git remote add origin2 https://$GITHUB_TOKEN@github.com/rmathew8-gh/Pelican.Blog
              # git push origin2 gh-pages

              echo "done and done"
              # git push origin gh-pages


