name: deploy

on: 
    push:
        branches:
            - master

jobs:
    build-x1:
        runs-on: ubuntu-latest

        steps:
          - name: full checkout
            uses: actions/checkout@v3

          - name: Set up Python 3.8
            uses: actions/setup-python@v4            
            with:
              python-version: '3.10' 

          - run: |
              # pip install invoke pelican[markdown]
              pip install -r requirements.txt
              env > /tmp/x.env
              pelican content -s publishconf.py
              ghp-import output -m "abc roy"
              # git push origin gh-pages


