name: deploy

on: 
    push:
        branches:
            - master

jobs:
    build-x1:
        runs-on: ubuntu-latest

        # permissions:
        #   contents: write
        #   # pull-requests: write
        #   # issues: write
        #   # repository-projects: write


        steps:
          - name: full checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Set up Python 3.8
            uses: actions/setup-python@v4            
            with:
              python-version: '3.10' 

          - name: Create a Release
            run: |
              pip install -r requirements.txt
              env > /tmp/x.env

              git config --global user.email "rmathew8@gmail.com"
              git config --global user.name "Roy Mathew"

              pelican content -s publishconf.py
              ghp-import output -p -n -m "Sunday 11:17 am"

              # echo "git checkout gh-pages"
              # git checkout gh-pages

              # git add output
              # git commit -m "[ci skip] Automated deployment to GitHub Pages on $(date +%s%3N)"
              # git push --force origin gh-pages

              echo "done and done"
