name: Discord message
on:
  [issue_comment] # github.event_name == issue_comment
        
jobs:
  test:
    if: github.actor == 'annsudo' || github.actor == 'xnektos/act' 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Payload
      run: |
        echo "The github context is:"
        echo "${{ toJson(github) }}"
    - name: Event name
      run: echo "Event name ${{ github.event_name }}"
    # - name: if Issue Comment   
    #   if: ${{ github.event_name =='issue_comment' }}
    #   run: echo "Event action ${{ github.event.action }}."
    # - name: Publish comment
    #   uses: ./ # Uses an action in the root directory
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
    #     DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

      
 
